services:
  db:
    image: postgres:16-alpine
    container_name: web-itmo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bruska
      POSTGRES_USER: bruska
      POSTGRES_PASSWORD: bruska
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bruska -d bruska"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-itmo-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://bruska:bruska@db:5432/bruska?sslmode=disable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL:-http://localhost:8080/bruska}
    container_name: web-itmo-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_API_URL: http://backend:8080/bruska

volumes:
  postgres_data:

# http://91.229.91.164:8080/bruska
